### PR TITLE
Primary key fix

### PR DESCRIPTION
**Pull request by rexmas**
Fixes crash when mapping primary keys.

### CODE REVIEW

**Comment by rexmas** [comment]
Confused why this is failing. Passes locally :(

**Comment by minuscorp** [comment]
Seems like libc++.dylib might not be in the project settings or the schema is not shared maybe?

**Comment by rexmas** [comment]
Scheme is definitely shared. Never had to include libc++.dylib directly before...

**Comment by rexmas** [comment]
I just switched from using `-sdk` to `-destination` (like described in Apple's documentation) and :boom: it worked. ¯_(ツ)_/¯

**Comment by minuscorp** [comment]
Seems legit. :laughing:

**Comment by rexmas** [comment]
@minuscorp have to leave right now, will update the pod later tonight :+1:

**Comment by minuscorp** [comment]
Nice work right here. Awesome!

**Comment by rexmas** [comment]
Pod's been updated in cocoapods :+1:

**Pull request merged**
